### ISSUE TITLE
TaliStation's Distribution and scrubber networks are connected together

### ISSUE THREAD

**Issue by Gboster-0** [Quasar-13/Quasar-13#784]
Its linked SOMEWHERE, who knows where

Reproduction:
1. Talistation gets voted on
2. You see distribution and waste pipes having the same pressure and same gasses

**Comment by BootlegBow** [comment]
what the actual fuck

**Comment by Gboster-0** [comment]
Aye, found where it is. Its in the incinerator

**Comment by Gboster-0** [comment]
Welp, quess the issue's gone.
